import '../css/main.scss';
import '../css/btn.scss';
import '../css/font.scss';
import 'jquery/dist/jquery.min.js';
import 'popper.js/dist/esm/popper.min.js';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.min.js';

import '../img/Banner-01.jpg'
import '../img/globe-logo.png'
import '../img/go-bear-logo.png'
import '../img/golden-haven-logo.png'
import '../img/metro-logo.svg'
import '../img/powered-by-echo.png'
import '../img/primer-logo.png'
import '../img/UNICEF_Logo.svg'
import '../img/kast-logo.svg'
import '../img/kast-logo-white.svg'
import '../img/send-broadcast.jpg'
import '../img/contacts.jpg'
import '../img/dashboard.jpg'
import '../img/reminder.jpg'